# Generated by Django 4.2.3 on 2023-07-18 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangorental', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing',
            new_name='Product',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_on_listing',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_on_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_on_product', to='djangorental.product'),
        ),
    ]
