# Generated by Django 4.2.3 on 2023-07-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorental', '0003_alter_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='product',
            name='image_file',
            field=models.ImageField(default='default.jpg', upload_to='product_images'),
        ),
    ]
