# Generated by Django 4.2.3 on 2023-07-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorental', '0004_remove_product_imageurl_product_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/'),
        ),
    ]
