# Generated by Django 4.2.3 on 2023-07-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorental', '0005_alter_product_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
