# Generated by Django 4.2.3 on 2023-07-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorental', '0006_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bullet_points',
            field=models.TextField(blank=True),
        ),
    ]
