# Generated by Django 4.2.3 on 2023-07-19 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangorental', '0007_product_bullet_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bullet_points',
        ),
    ]
