# Generated by Django 4.2.3 on 2023-07-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorental', '0008_remove_product_bullet_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bullet_points',
            field=models.TextField(blank=True),
        ),
    ]
