# Generated by Django 4.2.3 on 2023-07-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangorental', '0013_alter_userprofile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='number',
        ),
    ]
