# Generated by Django 4.2.3 on 2023-07-19 09:30

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('djangorental', '0014_remove_userprofile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
