# Generated by Django 4.2.3 on 2023-07-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorental', '0015_userprofile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
